version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.7
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
    - 8.4.0
    - 8.4.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
